#define RB_02_DISPLAY_TOUCH 1
#define RB_02_DISPLAY_SIZE RB_02_DISPLAY_28
#define RB_LICENSE_TYPE RB_LICENSE_TYPE_COMMERCIAL
#define RB_PRODUCT_LINE 5
#define RB_ENABLE_USB_FLARM 1
#define RB_ENABLE_CONSOLE 1
