#define RB_02_DISPLAY_SIZE RB_02_DISPLAY_17
#define RB_PRODUCT_LINE 2
#define RB_ENABLE_TRN 1
#define RB_LICENSE_TYPE RB_LICENSE_TYPE_COMMUNITY
#define RB_ENABLE_GPS 1
#define RB_ENABLE_UART 1
#define RB_ENABLE_WIFI 1

