#define RB_02_DISPLAY_TOUCH 1
#define RB_02_DISPLAY_SIZE RB_02_DISPLAY_28
#define RB_LICENSE_TYPE RB_LICENSE_TYPE_COMMUNITY
#define RB_PRODUCT_LINE 7
#define RB_TOUCH_DEBUG 1
//#define RB_TOUCH_WORKAROUND_MAX_X 480

