#define RB_02_DISPLAY_TOUCH 1
#define RB_02_DISPLAY_SIZE RB_02_DISPLAY_28
#define RB_LICENSE_TYPE RB_LICENSE_TYPE_COMMUNITY
#define RB_PRODUCT_LINE 2
#define RB_ENABLE_ATT 1
#define RB_ENABLE_TRK 1
#define RB_ENABLE_GPS 1
#define RB_ENABLE_UART 1
