#define RB_02_DISPLAY_TOUCH 1
#define RB_LICENSE_TYPE RB_LICENSE_TYPE_COMMUNITY
#define RB_02_DISPLAY_SIZE RB_02_DISPLAY_21
#define RB_PRODUCT_LINE 4
#define RB_ENABLE_EMS 1
#define RB_ENABLE_CONSOLE 1
//#define RB_ENABLE_UART 1
